### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by plaseastol** [zidaneho/SamiraMod#7]
hi i'm really a fan of your samira mod,though this mod has been made perfectly,i still meet something wrong.i know in vision 1.4.1 and 1.4.0 the problem that samira's attack speed influenced by frame per second has been solved,but now it is usual that samira's model would be stuck in attack procession.i dont know how it appear,but since it has appeared in a single game,it will follow you all game procession.In game,it looks like you just do the start of one attack posture,and then you seems like frozen,you wouldn't recover even if this attack is end;

https://github.com/user-attachments/assets/1b59f0d5-fd15-4bfa-8f25-990d76a6b9fe

**Comment by zidaneho** [comment]
Thanks for the feedback!

I think I have figured out this issue. It seems that slashing animations have 0 animation speed when players dash into enemies. Just in case, I have completely removed the animation speed of slashing attacks, because their animations are not supposed to scaled with attack speed.

I will be pushing this update in a couple of minutes.
